### ISSUE TITLE
bitrate menu opens at the start of every episode

### ISSUE THREAD

**Issue by CoralCarl** [jangxx/netflix-1080p#8] opened 2020-08-30 12:17 UTC
Title

**Comment by jangxx** [comment] 2020-08-30 14:04
Yes that is expected behavior and supposed to happen. I'm not really sure what your problem is. Is it staying open or something? Usually it should just flash very briefly. If you don't want the extension to automatically force the highest bitrate you can disable it in the options menu of course.

**Comment by CoralCarl** [comment] 2020-08-30 14:07
It stays open on some ocoassions, I'll try to single out when exactly happens and come back to you.

**Comment by coxackie** [comment] 2020-09-22 08:53
I confirm that it quite often stays open, but I am not sure what could be causing this...

**Comment by georgeat8** [comment] 2020-10-31 23:52
Can also confirm that it stays open permanently and I usually get it when the next episode of a series plays. On page refresh it's gone.

**Comment by TobySkarting** [comment] 2020-11-08 09:27
I found that it happens when Automatically Skip Intro from Super Netflix is enabled.

**Comment by jangxx** [comment] 2020-11-08 20:46
I have just pushed a possible fix for the issue. Please try it out and tell me if it works for you. In my own experiments it has worked pretty well.

**Comment by georgeat8** [comment] 2020-11-10 20:58
Seems that the issue is fixed, at least after about 2-3h of watching, nothing got stuck. Will update if it does happen again.

**Comment by coxackie** [comment] 2020-11-13 21:55
If this is indeed fixed, @jangxx  could you push an updated release? Many many thanks!

**Comment by jangxx** [comment] 2020-11-14 18:27
Version 1.23.0 has been released, which should fix this issue, so I'm closing this for now.

**Closed by jangxx** 2020-11-14 18:27 UTC
