### ISSUE TITLE
doesnt work today

### ISSUE THREAD

**Issue by iiianthony** [jangxx/netflix-1080p#22] opened 2021-05-15 06:04 UTC
it works perfectly before, but it doesn't work today.
anyone has the same problem?

**Comment by jangxx** [comment] 2021-05-15 15:33
Yes, I can confirm that there is a problem, because Netflix changed the URL of their CDN. I'm working on it and a new version should be available soon.

**Comment by jangxx** [comment] 2021-05-15 15:57
Okay, I have just published version 1.24.0 which should fix the issue. Please let me know if it does and then we can close this issue.

**Comment by B1LMAN** [comment] 2021-05-16 01:00
1.24.0 doesn't seem to force 1080p for me, and I'm very sure I've installed it correctly.

**Comment by Kron155** [comment] 2021-05-16 01:55
Thank you for keeping this alive, but 1.24.0 doesn't force 1080p for me neither.

**Comment by iiianthony** [comment] 2021-05-16 04:17
Thank you for keeping this alive first because it is very useful to me. But, I have the same problem with other guys.
It doesn't force 1080p for me and no bitrate option can choose when I click that icon.

**Comment by jangxx** [comment] 2021-05-16 10:40
So it looks like I'm going to need more information on this, because it works for me and I'm now thinking this might be a regional thing, where the CDN URL changes depending on your location.

To confirm this, please do the following:

1. Open netflix.com (you need to be logged in)
2. Press Ctrl + Shift + I to open the DevTools
3. Reload the page
4. Follow this image to find the URL of the loaded JavaScript file: https://i.imgur.com/Yy7SM2A.png
5. Post the URL here (underlined in red in the picture)

I'm pretty sure we should be able to figure this out, but I need some more data before I can fix this.

**Comment by Kron155** [comment] 2021-05-16 11:49
This is for Czech Republic (CZ):
https://occ-web-h1.a.nflxso.net/sec/en_us/ffe/player/html/cadmium-playercore-6.0030.399.911.js

**Comment by B1LMAN** [comment] 2021-05-16 13:49
> So it looks like I'm going to need more information on this, because it works for me and I'm now thinking this might be a regional thing, where the CDN URL changes depending on your location.
> 
> To confirm this, please do the following:
> 
> 1. Open netflix.com (you need to be logged in)
> 2. Press Ctrl + Shift + I to open the DevTools
> 3. Reload the page
> 4. Follow this image to find the URL of the loaded JavaScript file: https://i.imgur.com/Yy7SM2A.png
> 5. Post the URL here (underlined in red in the picture)
> 
> I'm pretty sure we should be able to figure this out, but I need some more data before I can fix this.

https://occ-web-h2.a.nflxso.net/sec/en_us/ffe/player/html/cadmium-playercore-6.0030.399.911.js

**Comment by jangxx** [comment] 2021-05-16 14:21
To me this looks like `*://*.a.nflxso.net/sec/*/ffe/player/html/*` should match all the URLs now, unless they are different on other continents. I have just published version 1.24.1, which should work for the URLs mentioned in this thread. If someone else has the same problem, please use the process outlined above to get the URL of the player and post it here so that I can expand the matching pattern even further.

**Comment by iiianthony** [comment] 2021-05-16 15:14
It works!!! Really want to say thank you to you. I can enjoy Netflix again now :)

**Comment by B1LMAN** [comment] 2021-05-16 15:26
Yup, I can confirm it works for me, too.

**Comment by ChubbyBoySlim** [comment] 2021-05-16 17:01
> So it looks like I'm going to need more information on this, because it works for me and I'm now thinking this might be a regional thing, where the CDN URL changes depending on your location.
> 
> To confirm this, please do the following:
> 
> 1. Open netflix.com (you need to be logged in)
> 2. Press Ctrl + Shift + I to open the DevTools
> 3. Reload the page
> 4. Follow this image to find the URL of the loaded JavaScript file: https://i.imgur.com/Yy7SM2A.png
> 5. Post the URL here (underlined in red in the picture)
> 
> I'm pretty sure we should be able to figure this out, but I need some more data before I can fix this.

Doesn't work for me either here in Finland. https://assets.nflxext.com/en_us/ffe/player/html/cadmium-playercore-6.0030.399.911.js

Thank you for your work hard work regarding this!

**Comment by jangxx** [comment] 2021-05-16 17:06
That is one of the old URLs that were already covered before, so you seem to be having a different problem. Do you see the output `netflix_max_bitrate.js enabled` in the DevTools console? If you don't the extension is not installed correctly (or you have the max bitrate option disabled).

**Comment by ChubbyBoySlim** [comment] 2021-05-16 17:16
It seems that I am at fault here. Site access for the extension has been enabled but now that I look more careful the extension itself is permanently disabled by Chrome. "This extension is not listed in the Chrome Web Store and may have been added without your knowledge."

I wonder if there is easy way to enable it?

**Comment by jangxx** [comment] 2021-05-16 17:17
Did you follow the instructions in the README? It should work if you follow them.

**Comment by ChubbyBoySlim** [comment] 2021-05-16 17:21
Go to the Releases section and download the latest .crx file
Go to the Extensions settings of your Chrome browser and toggle "Developer Mode" in the upper right corner.
Drag the downloaded .crx file into the Extensions window to install it 

Yep. Chrome 90.0.4430

**Comment by jangxx** [comment] 2021-05-16 17:35
Well I don't know what to tell you, but it seems to work for everyone else including me and I can't replicate your issue, so maybe you just need to google that for yourself.

**Comment by Kron155** [comment] 2021-05-16 17:45
You can also try this: https://support.google.com/chrome/a/answer/187202?hl=en#zippy=%2Cwindows
After you add that policy open gpedit.msc and go to: 
Local Computer Policy > Computer Configuration > Administrative Templates > Google > Google Chrome > Extensions > Configure extension installation whitelist > enable it and write there the extension ID should be this: **mkimjnfbbelfbcoecfnpdffkongeffjl** (Should be same for everybody, but not 100% sure).
You will find it at chrome://extensions/ when you click on  "Developer Mode" and in the box with extension you will find ID.

**Comment by Mouse753** [comment] 2021-05-16 17:46
https://assets.nflxext.com/en_us/ffe/player/html/cadmium-playercore-6.0030.399.911.js

any title I play from universal studios, 1080p is not working

**Comment by Kron155** [comment] 2021-05-16 17:48
It is working now. Netflix is forced in 1080p. Thank you,

**Comment by liam1206201** [comment] 2021-05-19 09:39
https://assets.nflxext.com/en_us/ffe/player/html/cadmium-playercore-6.0030.511.911.js
I have still problem, 1080 is not working in S.Korea

**Comment by jangxx** [comment] 2021-05-19 10:00
Everyone who is posting an URL starting with `assets.nflxext.com` has a problem that is different from the one this issue is about. You guys should check if the extension is installed correctly and if your problem has already been covered in a previous issue (like 1080p not working for some titles no matter what, because Netflix uses a different form of DRM for them). I am going to close this issue now, since the original problem has been fixed. If anyone else has a problem with the extension not loading, and the URL does **not** contain `assets.nflxext.com` or `a.nflxso.net`, please leave another comment here. For other general support please use the Discussions.

**Closed by jangxx** 2021-05-19 10:00 UTC
