### ISSUE TITLE
I can't see audio formats :(

### ISSUE THREAD

**Issue by tmac21** [jangxx/netflix-1080p#4] opened 2020-06-28 11:35 UTC
Hello sir, I can't see video formats. Like 2.0 - 5.1, pls fix it.

**Comment by jangxx** [comment] 2020-06-28 12:52
It works for me, both on my Linux desktop and my Macbook. Are you loading the extension correctly? If you load it as an unpacked extension, you need to checkout/download the patch-1 branch, not the master branch.

**Comment by tmac21** [comment] 2020-06-28 13:06
with 1.21.1 it's working, thanks so much, sir :) win10 cent browser.

**Comment by tmac21** [comment] 2020-06-28 13:18
at series dubbing and audio formats window opens every time :(, can you fix ?

**Comment by jangxx** [comment] 2020-06-28 18:09
No, it's supposed to close automatically, but if it doesn't you can simply hit Shift+Ctrl+Alt+S to close it.

**Comment by tmac21** [comment] 2020-07-19 00:49
This happens every time :(

![image](https://user-images.githubusercontent.com/26900671/87864586-adf21680-c972-11ea-9716-d3ca647269bd.png)

**Comment by jangxx** [comment] 2020-07-19 11:17
What can I say, except that you are the only person to ever report this. I can't reproduce your issue and there is nothing in the code that would open that window so it's probably a conflict with some other extension you have installed. Maybe try disabling all extensions and then re-enable them one at a time to get to the real culprit.

**Comment by jangxx** [comment] 2021-03-17 16:25
The bitrate menu issue has been fixed in version 1.23.0.

**Closed by jangxx** 2021-03-17 16:25 UTC
